### ISSUE TITLE
Error when attempting to install the module

### ISSUE THREAD

**Issue by gicelte** [Jadlog/magento-2.3#1]
How do I create this table?

[Zend_Db_Statement_Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_magento.jadlog_modalidades' doesn't exist, query was: INSERT INTO `jadlog_modalidades` (`codigo`, `descricao`, `modal`, `at
  ivo`) VALUES (?, ?, ?, ?)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_magento.jadlog_modalidades' doesn't exist

**Comment by tuping** [comment]
This module is still in BETA, so you need to follow the instructions.

Basically you need to clone this repo and add it as a local repository for composer. Then you can use:
```bash
composer require jadlog/embarcador
php bin/magento module:status
php bin/magento module:enable Jadlog_Embarcador
php bin/magento setup:di:compile
php bin/magento setup:upgrade
```

Look at https://github.com/Jadlog/magento-2.3/blob/master/doc/Jadlog%20-%20Magento.md

----


Por tratar-se de versão **BETA** a instalação deve ser feita copiando o código fonte diretamente no servidor.

*O passo a passo a seguir supõe que o Magento esteja instalado em **/var/www/html***:

1. Clone esse repositório diretamente no seu servidor numa pasta apropriada, por exemplo:
```bash
mkdir /var/www/html/jadlog
cd /var/www/html/jadlog
git clone https://github.com/Jadlog/magento-2.3.git
```

2. Configure o repositório local:
```bash
cd /var/www/html
composer require magento/magento-composer-installer
composer config repositories.jadlog-embarcador path /var/www/html/jadlog/magento-2.3/src/app/code/Jadlog/Embarcador
```

3. Habilite o módulo:
```bash
cd /var/www/html/
composer require jadlog/embarcador
php bin/magento module:status
php bin/magento module:enable Jadlog_Embarcador
php bin/magento setup:di:compile
php bin/magento setup:upgrade
