### ISSUE TITLE
Conflitos no Módulo Expresso e Pickup

### ISSUE THREAD

**Issue by rjslegall** [Jadlog/magento-2.3#3]
Conflitos no Módulo Expresso e Pickup

Condições da instalação
- Magento 2.3.5-p1
- PHP 7.3
- Sem outros módulos de frete (Frenet e outros...)

Configuração do módulo
- URL Frete: http://www.jadlog.com.br/embarcador/api/frete/valor
- URL Pedido: http://www.jadlog.com.br/embarcador/api/pedido/incluir
- URL Tracking: http://www.jadlog.com.br/embarcador/api/tracking/consultar
- URL Serviço "MyPudo": http://www.jadlog.com.br/embarcador/api/pickup/myPudo

Retornos Expresso Jadlog
- Notice: Undefined index: frete in /home/(minha loja)/public_html/app/code/Jadlog/Embarcador/Model/Carrier/JadlogExpresso.php on line 47
- jquery.js:10260 POST https://(minha loja)/index.php/rest/default/V1/guest-carts/(token)/set-payment-information 400
- Retorna valores de frete no frontend

Retornos Pickup Jadlog
- O pedido não corresponde a nenhuma rota. (URL inválido)
- Notice: Undefined index: frete in /home/(minha loja)/public_html/app/code/Jadlog/Embarcador/Model/Carrier/JadlogPickup.php on line 58
- jquery.js:10260 GET https://(minha loja)/index.php/rest/default/V1/jadlog_embarcador/get-pudo-list/01034-902/?_=(código)
- Não retorna valores de frete e locais para reirada no frontend mas no log sim

Hoje temos contrato com a Jadlog e gostaríamos de utilizar o módulo em nossa loja visto que temos muita demanda. Para que isso seja possível precisaremos solucionar estes problemas. 

- Podem ajudar a solucionar? 
- Existe um demo do módulo funcionado na versão mais recente que possam disponibilizar?
- Estes problemas já foram reproduzidos em outra instalação?

**Comment by rjslegall** [comment]
Utilizando:
- URL Serviço "MyPudo": http://www.jadlog.com.br/embarcador/api/pickup/pudos

Tenho o retorno no console:

jquery.js:259 Uncaught Error: cannot call methods on modal prior to initialization; attempted to call method 'openModal'
    at Function.error (jquery.js:259)
    at HTMLDivElement.<anonymous> (widget.js:186)
    at Function.each (jquery.js:376)
    at jQuery.fn.init.each (jquery.js:142)
    at jQuery.fn.init.$.fn.<computed> [as modal] (widget.js:182)
    at UiClass.reloadPudos (pudo-form.js:122)
    at UiClass.showPopupJadlogPickup (pudo-form.js:54)
    at UiClass.<anonymous> (pudo-form.js:100)
    at Function.notifySubscribers (knockout.js:1320)
    at Function.valueHasMutated (knockout.js:1538)

Este erro também ocorre nas condições relatadas acima.

**Comment by sistemas-jadlog** [comment]
Para ajudar a solucionar o problema favor entrar em contato conosco através dos canais de atendimento disponíveis no site http://www.jadlog.com.br.

**Nunca forneça seu token em ambiente público**

**Comment by rjslegall** [comment]
> Conflitos no Módulo Expresso e Pickup
> 
> Condições da instalação
> 
> * Magento 2.3.5-p1
> * PHP 7.3
> * Sem outros módulos de frete (Frenet e outros...)
> 
> Configuração do módulo
> 
> * URL Frete: http://www.jadlog.com.br/embarcador/api/frete/valor
> * URL Pedido: http://www.jadlog.com.br/embarcador/api/pedido/incluir
> * URL Tracking: http://www.jadlog.com.br/embarcador/api/tracking/consultar
> * URL Serviço "MyPudo": http://www.jadlog.com.br/embarcador/api/pickup/myPudo
> 
> Retornos Expresso Jadlog
> 
> * Notice: Undefined index: frete in /home/(minha loja)/public_html/app/code/Jadlog/Embarcador/Model/Carrier/JadlogExpresso.php on line 47
> * jquery.js:10260 POST https://(minha loja)/index.php/rest/default/V1/guest-carts/(token)/set-payment-information 400
> * Retorna valores de frete no frontend
> 
> Retornos Pickup Jadlog
> 
> * O pedido não corresponde a nenhuma rota. (URL inválido)
> * Notice: Undefined index: frete in /home/(minha loja)/public_html/app/code/Jadlog/Embarcador/Model/Carrier/JadlogPickup.php on line 58
> * jquery.js:10260 GET https://(minha loja)/index.php/rest/default/V1/jadlog_embarcador/get-pudo-list/01034-902/?_=(código)
> * Não retorna valores de frete e locais para reirada no frontend mas no log sim
> 
> Hoje temos contrato com a Jadlog e gostaríamos de utilizar o módulo em nossa loja visto que temos muita demanda. Para que isso seja possível precisaremos solucionar estes problemas.
> 
> * Podem ajudar a solucionar?
> * Existe um demo do módulo funcionado na versão mais recente que possam disponibilizar?
> * Estes problemas já foram reproduzidos em outra instalação?

.....

**Comment by rjslegall** [comment]
...
